### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by Ojjjjjlol** [prajwollamichhane11/PDF-Handling-With-Python#2]
I'm getting an error in your code: 
#

from io import StringIO
from pdfminer.pdfinterp import PDFPageInterpreter, PDFResourceManager
from pdfminer.pdfpage import PDFPage
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
 
# PDFMiner Analyzers
rsrcmgr = PDFResourceManager()
sio = StringIO()
codec = "utf-8"
laparams = LAParams()
device = TextConverter(rsrcmgr, sio, codec=codec, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
 
# path to our input file
pdf_file = "sample.pdf"
 
# Extract text
pdfFile = open(pdf_file, "rb")
for page in PDFPage.get_pages(pdfFile):
   interpreter.process_page(page)
fp.close()
 
# Return text from StringIO
text = sio.getvalue()
 
print(text)
 
# Freeing Up
device.close()
sio.close()
#
issue here: fp.close()
NameError: name 'fp' is not defined

I'm not a programmer, but i think <code>fp.close</code> should be changed to <code>pdfFile.close()</code>

**Comment by prajwollamichhane11** [comment]
Yes, you are right. Thanks!
