### ISSUE TITLE
Wrong installation instruction for PyMuPDF

### ISSUE THREAD

**Issue by JorjMcKie** [prajwollamichhane11/PDF-Handling-With-Python#3]
Hi, I am the author of PyMuPDF.
In your description on how to install PyMuPDF you write

```
pip install pymupdf
pip install fitz
```
This is wrong: `fitz` is a separate package that has nothing to do with PyMuPDF. Even worse:
Package `fitz` **_must not be installed in the same environment!_** The reason: PyMuPDF uses the name "fitz" as its top-level identifier.
PyMuPDF and fitz (a package that is young and still in its beta) must be installed in different (virtual) environments.
The correct installation procedure for PyMuPDF (works on Windows, Linux and Mac):
```
python -m pip install -U pip
python -m pip install pymupdf
```

**Comment by prajwollamichhane11** [comment]
Thanks for the suggestions. Pymupdf is really a good package for PDF handling.
